export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';


export const ADD_CART_FROM_LOCAL = 'ADD_CART_FROM_LOCAL';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const DELETE_ITEM_TO_CART = 'DELETE_ITEM_TO_CART';
export const DELETE_ONE_ITEM_TO_CART = 'DELETE_ONE_ITEM_TO_CART';
export const RESET_CART = 'RESET_CART';

export const OPEN_MODAL_PRODUCT = 'OPEN_MODAL_PRODUCT';
export const CLOSE_MODAL_PRODUCT = 'CLOSE_MODAL_PRODUCT';
export const WITCH_MODAL_PRODUCT = 'WITCH_MODAL_PRODUCT';
export const CHOOSE_MODAL_PRODUCT = 'CHOOSE_MODAL_PRODUCT'

export const IS_VISIBLE_SPINNER = 'IS_VISIBLE_SPINNER';
export const IS_NOT_VISIBLE_SPINNER = 'IS_NOT_VISIBLE_SPINNER';





